version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - froi
  assignees:
  - froi
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: chai
    versions:
    - 4.3.1
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.1.0
    - 5.1.1
    - 5.1.2
